### PR TITLE
attempt to fix #85: git clone using a keypair protected by a passphrase

### LINKED ISSUE #85: git clone using a keypair protected by a passphrase
- clj-jgit/clj-jgit {:mvn/version "1.1.0"}

I have a keypair generated with a passphrase and I have a keypair with no passphrase.

I can use the keypair without a passphase to clone a repo:
```clojure
(git/with-identity
  {:name      "no_passphrase"
   :trust-all true}
  (def my-repo (git/git-clone
                 "git@github.com:babashka/sci.git"
                 :dir "local-folder/sci")))
```

If I use the keypair with a passphase:
```clojure
(git/with-identity
  {:name      "id_rsa"
   :pw        "<secret>"
   :trust-all true}
  (def my-repo (git/git-clone
                 "git@github.com:babashka/sci.git"
                 :dir "local-folder/sci")))
```

I get an error:
`Caused by: javax.security.auth.login.FailedLoginException: No password data for encrypted resource=<path>/.ssh/id_rsa`

so I know the key file is found ok.

I see the `*ssh-key-passphrase*` binding correctly set in the debugger when the git-clone is executed but it doesn't seem to be used later.   Anybody have a working example or an idea please?

### PR DESCRIPTION
**Pull request by humphrej**
Seems to work: tested with git-clone, git-pull, git-push.  Feedback welcome!

### CODE REVIEW

File: src/clj_jgit/porcelain.clj [hunk 1]
```diff
@@ -476,7 +479,9 @@
   (-> (Git/cloneRepository)
       (.setURI uri)
       ^TransportCommand (.setCredentialsProvider *cred-provider*)
-      (.setTransportConfigCallback *transport-callback*)))
+      (.setTransportConfigCallback *transport-callback*)
+      (.setCredentialsProvider(UsernamePasswordCredentialsProvider. nil *ssh-key-passphrase*))
```
Comment (edannenberg) [inline src/clj_jgit/porcelain.clj:483]: This essentially overrides any `*cred-provider*` set by the user. Which I guess is fine if we document it but maybe it would be better to alter the `with-identity` macro to set `*cred-provider*` accordingly if `*ssh-key-passphrase` is provided. Then it should work transparently for all commands.

**Review by edannenberg — CHANGES_REQUESTED** [review]
Thank you for picking this up, and sorry for the late reply! Busy days.

File: src/clj_jgit/porcelain.clj (hunk 1 above)
Comment (humphrej) [reply src/clj_jgit/porcelain.clj]: Thanks, I see your point - I added another commit so that clone-cmd is unchanged and the credentials provider is set in with-identity.

Comment (edannenberg) [reply src/clj_jgit/porcelain.clj]: Thanks, looks good! There was a little issue with `:trust-all? true` and the `user-pass-provider` proxy impl in general, which I fixed earlier. I'll try to cut a new release soonish.
